name: Reusable Deploy
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Short Commit Sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}